---
# tasks file for jenkins
- name: Download oracle Java 8
  become: yes
  become_user: "{{ automation_user_name }}"
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
    dest: /tmp/jdk-8u131-linux-x64.rpm
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie

- name: Check that oracle_java.rpm has been downloaded
  become: yes
  become_user: "{{ automation_user_name }}"
  stat:
    path: /tmp/jdk-8u131-linux-x64.rpm
  register: java_rpm_result

- name: Install java rpm downloaded
  become: yes
  yum:
    name: /tmp/jdk-8u131-linux-x64.rpm
    state: present
  when: java_rpm_result.stat.exists
  register: java_installed

- name: Set $JAVA_HOME
  become: yes
  become_user: "{{ automation_user_name }}"
  blockinfile:
    path: /home/{{ automation_user_name }}/.bashrc
    block: |
      export JAVA_HOME=/usr/java/jdk1.8.0_131/
      export PATH=$PATH:$JAVA_HOME/bin