---
# tasks file for automation_agent 
- name: Disable SELinux
  become: yes
  selinux:
    state: disabled

- name: Install yum packages
  become: yes
  yum: 
    name: 
      - zip
      - maven
      - unzip
    state: present

- name: Create runner_agent for jenkins
  become: yes
  user: 
    name: "{{ automation_user_name }}"
    shell: /bin/bash
    groups: wheel
    # Aa123456
    password: $6$YXyiXEbkq7Ous69G$XUOjd5xwSaRbrF4I.AHr2o77oe7iqU2aPEtg7BX3kxZDN97hibAP4Z9GBMwS8cTIyZpwZQblw6yDBAMGVLoBj.
  register: user_created 

- name: Copy skel bashrc to runner_agent home
  become: yes
  become_user: "{{ automation_user_name }}"
  copy:
    src: /etc/skel/.bashrc
    dest: /home/{{ automation_user_name }}/.bashrc
    remote_src: yes
  when: user_created 

- name: Download oracle Java 8
  become: yes
  become_user: "{{ automation_user_name }}"
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
    dest: /tmp/jdk-8u131-linux-x64.rpm
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie

- name: Check that oracle_java.rpm has been downloaded
  become: yes
  become_user: "{{ automation_user_name }}"
  stat:
    path: /tmp/jdk-8u131-linux-x64.rpm
  register: java_rpm_result

- name: Install java rpm downloaded
  become: yes
  yum:
    name: /tmp/jdk-8u131-linux-x64.rpm
    state: present
  when: java_rpm_result.stat.exists
  register: java_installed

- name: Set $JAVA_HOME
  become: yes
  become_user: "{{ automation_user_name }}"
  blockinfile:
    path: /home/{{ automation_user_name }}/.bashrc
    block: |
      export JAVA_HOME=/usr/java/jdk1.8.0_131/
      export PATH=$PATH:$JAVA_HOME/bin

- name: Download Android ide and sdk tools
  become: yes
  become_user: "{{ automation_user_name }}"
  get_url:
    url: https://dl.google.com/dl/android/studio/ide-zips/3.4.1.0/android-studio-ide-183.5522156-linux.tar.gz
    dest: /home/{{ automation_user_name }}/android-studio-ide-183.5522156-linux.tar.gz
  register: android_sdk_downloaded

- name: Unzip sdk tools
  become: yes
  become_user: "{{ automation_user_name }}"
  unarchive:
    src: /home/{{ automation_user_name }}/android-studio-ide-183.5522156-linux.tar.gz
    dest:  /home/{{ automation_user_name }}/
    remote_src: yes
  when: android_sdk_downloaded
  register: android_tools_sdk_unziped
    
- name: Set $ANDROID_HOME
  become: yes
  become_user: "{{ automation_user_name }}"
  blockinfile:
    path: /home/{{ automation_user_name }}/.bashrc
    block: |
      # Set Android Home
      export ANDROID_HOME=/home/{{ automation_user_name }}/Android/Sdk
      export PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/28.0.3"
  when: android_tools_sdk_unziped

- name: Add EPEL repository so node.js can be installed
  become: yes
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  register: epel_enabled

- name: Install node.js through yum
  yum:
    name: nodejs 
    state: present
    update_cache: yes

- name: Install appium through npm 
  become: yes
  become_user: "{{ automation_user_name }}"
  npm:
    name: appium
    version: '1.12.1'
    global: yes


