- hosts: redisserver
  become: yes
  remote_user: vagrant
  gather_facts: no
  pre_tasks:
  - name: 'install python2'
    raw: sudo apt-get -y install python
  roles:
    -   roles/nextcloud
    -   roles/redis
    -   roles/filebeat