---
# tasks file for redis
- name: Update repositories cache and install "redis" package
  apt:
    name: redis
    state: present

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"

- name: Test server PING
  command: redis-cli -h 127.0.0.1 -p {{ redis_port }} ping
  