# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPzVub/VhDwpbOt+tOJ8Rv4OcjI73pmxsClAgVx+DX4Z+8iwQ8qFhM9FNUS9MIOws4sCSjk0tRCraW0lp6RHbilrwVPkPTmwzRQg17m0B0HtPrjVpgBM8FHiCiXlB31xiT4PqDTga9boWSllR0PrOct+7AIPq6fnzSF0LT3XNnpeKxj+BZEmRqNpZ57+U6OPdFK7S1vbPnnzG4F87UQElhZ9GEd4R6lbvw9hDUBeFHGs6UDQJBFwu14ls+h30ApcLliCWCbqFcVX7rOV1zjcfJlqi1XazZVsVECTKaXceUtUx7elMOgFqewF1lDSI90nTXuaIaX1UXzVZH9t+RlBOJ matt@localhost.localdomain
    " >> /home/vagrant/.ssh/authorized_keys &&
    sudo systemctl restart sshd.service &&
    # sudo dnf update -y
    SHELL

    # config.vm.provision "shell", inline: <<-SHELL
    # wget https://github.com/rancher/k3s/releases/download/v0.5.0/k3s -O /home/vagrant/k3s && sudo mv -v /home/vagrant/k3s /usr/bin/ && sudo chmod +x /usr/bin/k3s
    # SHELL
  
    config.vm.define "cockpit" do |m|
      m.vm.box = "fedora/29-cloud-base"
      m.vm.hostname = 'cockpit'
      
    
      m.vm.network :"public_network", bridge: "wlp1s0", ip: "192.168.0.200"
    
      m.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--name", "cockpit"]
      end
    end
  end
  