# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  ## Add vagrant ssh key for ansible
  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTeutXeah1PJKTwsVJXpXSOhsYCYSJ/FHOlN7i6QxAwM8lxbK4vTlJ/iIiIyioqaht4xjEoy5ued15hNJo699aRV2GQzQO7b8LEDCmEOVykN+j2sqFEbTjm9yTC35tFbpY30Nnpirzcq6XGdmy7ZbTx252ISssuMoOgnjWegXVGw+sD4wno6aw+ICElB0QTZQCW4H2/Bf+fRbWHbIcVH2Wu3OYk/tonWG9A5ejph7lBdkk+sAmdlnrlKlHn3Rl2WPoWnJH48vqzobQE92nwVzB3sUcIIcpm1pFWeJqSNbLJMWynXf5qGRdOV1iFwI/9EGq/cbp/L6E0OBJkSn6P6F/ matt@localhost.localdomain" >> /home/vagrant/.ssh/authorized_keys
  sudo systemctl restart sshd.service
  SHELL

  config.vm.define "kimchi" do |m|
    m.vm.box = "bento/centos-7.6"
    m.vm.hostname = 'kimchi'
    
  
    m.vm.network :"public_network", bridge: "wlp1s0", ip: "192.168.0.250"
    

  
    m.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "kimchi"]
    end
  end
end


